[package]
name = "wally"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8.12"
serde_derive = "1.0.197"
sqlx = { version = "0.7.3", features = ["runtime-async-std-native-tls", "sqlite", "chrono"] }
tokio = {version = "1.37.0", features = ["full"] }
chrono = { version = "0.4.34", features = ["serde"] }

[dependencies.uuid]
version = "1.8.0"
features = [ "v4", "fast-rng"]

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
