[picture_config]
current_picture = "/Users/andresvelasco/Documents/pictures/wallpapers/pnDfPrHL-wallha.com.jpg"
playlist_enable = false
playlist_time = 0
folder_dir = "/Users/andresvelasco/Documents/pictures/wallpapers"
