-- Add migration script here
CREATE TABLE PICTURE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR2 not null,
    description VARCHAR2 not null,
    file BLOB not null,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE PLAYLIST(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pictureOrder INTEGER NOT NULL UNIQUE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    pictureId VARCHAR2 UNIQUE,
    FOREIGN KEY(pictureId) REFERENCES PICTURE(id) ON DELETE CASCADE
);